# Generated by Django 3.2.10 on 2023-03-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='leave_application_file_attachment',
            new_name='leave_application_file_path',
        ),
    ]
