# Generated by Django 3.2.10 on 2023-03-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0002_rename_leave_application_file_attachment_leaveapplication_leave_application_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
