# Generated by Django 3.2.10 on 2023-03-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0003_leaveapplication_approved_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.customuser'),
        ),
    ]
