# Generated by Django 3.2.10 on 2023-03-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0005_auto_20230309_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_created_by',
            new_name='super_user_ref',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='reporting_manager',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='people',
            name='base64',
        ),
        migrations.RemoveField(
            model_name='people',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='people',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='people',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='people',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='people',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='people',
            name='people_status',
        ),
        migrations.RemoveField(
            model_name='people',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='people',
            name='photo_path',
        ),
    ]
