# Generated by Django 3.2.10 on 2023-03-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0006_auto_20230314_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_reporting_manager_ref',
        ),
        migrations.AddField(
            model_name='people',
            name='user_reporting_manager_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reporting_manager_ref', to='eztimeapp.customuser'),
        ),
    ]
