# Generated by Django 3.2.10 on 2023-03-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0010_rename_people_ref_projects_people_ref_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprojectcategories',
            name='base64',
        ),
        migrations.RemoveField(
            model_name='taskprojectcategories',
            name='billable_type',
        ),
        migrations.RemoveField(
            model_name='taskprojectcategories',
            name='file_attachment',
        ),
        migrations.RemoveField(
            model_name='taskprojectcategories',
            name='file_attachment_path',
        ),
        migrations.AddField(
            model_name='center',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientsdms',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientsothercontactdetails',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocities',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocontinents',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocountries',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocountriescurrencies',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocurrencies',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geostates',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geosubcontinents',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geotimezones',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozones',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterleavetypes',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationcostcenters',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationcostcentersleavetype',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationcostcentersyearlist',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationdepartment',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationleavetype',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationroles',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpeoplegroup',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefixsuffix',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategories',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategorieschecklist',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategoriesfilestemplates',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstatusmaincategory',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstatussubcategory',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskprojectcategories',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskprojectcategories',
            name='task_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskprojectcategories',
            name='tpc_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskprojectcategorieschecklist',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeofindustries',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userleaveallotmentlist',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userleavelist',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersleaveapplications',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersleavemaster',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
