# Generated by Django 3.2.10 on 2023-04-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0011_auto_20230320_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role_name', models.CharField(blank=True, max_length=250, null=True)),
                ('module_name', models.CharField(blank=True, max_length=250, null=True)),
                ('permissions', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomCenter', to='eztimeapp.userrole'),
        ),
    ]
