# Generated by Django 3.2.10 on 2023-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0013_auto_20230420_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='module_name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
