# Generated by Django 3.2.10 on 2023-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0014_alter_userrole_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='task_project_category_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
