# Generated by Django 3.2.10 on 2023-06-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0016_projects_project_related_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprojectcategories',
            name='file_templates_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
