# Generated by Django 3.2.10 on 2023-06-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0017_taskprojectcategories_file_templates_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='request',
            field=models.CharField(blank=True, default='LEAVE_REQUEST', max_length=250, null=True),
        ),
    ]
