# Generated by Django 3.2.10 on 2023-07-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0018_leaveapplication_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user_ref',
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
        migrations.AddField(
            model_name='people',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
    ]
