# Generated by Django 3.2.10 on 2023-07-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0019_auto_20230703_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_working_days_all', models.JSONField(blank=True, null=True)),
                ('office_working_days', models.JSONField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp')),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last_Update_TimeStamp')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.customuser')),
            ],
        ),
    ]
