# Generated by Django 3.2.10 on 2023-07-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0020_officeworkingdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
