# Generated by Django 3.2.10 on 2023-07-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0021_customuser_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='conctact_person_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
