# Generated by Django 3.2.10 on 2023-11-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0022_organization_conctact_person_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.CharField(blank=True, max_length=250, null=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='last_update_timestamp')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.projects')),
            ],
        ),
    ]
