# Generated by Django 3.2.10 on 2023-11-22 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0024_auto_20231122_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CustomCenter', to='eztimeapp.center'),
        ),
    ]
