# Generated by Django 3.2.10 on 2023-11-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0025_alter_customuser_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='prefix_suffix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eztimeapp.prefixsuffix'),
        ),
    ]
