# Generated by Django 3.2.10 on 2023-12-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0026_alter_people_prefix_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
        migrations.AddField(
            model_name='masterleavetypes',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
        migrations.AddField(
            model_name='notificationcenter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
    ]
