# Generated by Django 3.2.10 on 2023-12-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0027_auto_20231203_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefixsuffix',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
    ]
