# Generated by Django 3.2.10 on 2023-12-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0028_auto_20231204_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatusmaincategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
    ]
