# Generated by Django 3.2.10 on 2023-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0029_projectstatusmaincategory_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdepartment',
            name='od_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organizationroles',
            name='or_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
