# Generated by Django 3.2.10 on 2024-02-06 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eztimeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.JSONField(blank=True, null=True)),
                ('time_spent', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('task_worked_list', models.JSONField(blank=True, null=True)),
                ('approved_state', models.CharField(blank=True, max_length=250, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('applied_date', models.CharField(blank=True, max_length=250, null=True)),
                ('applied_date_timestamp', models.CharField(blank=True, max_length=250, null=True)),
                ('approved_date_timestamp', models.CharField(blank=True, max_length=250, null=True)),
                ('approved_date', models.CharField(blank=True, max_length=250, null=True)),
                ('approved_date_time', models.DateTimeField(null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.customuser')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tm_clent', to='eztimeapp.clients')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='eztimeapp.customuser')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tm_project', to='eztimeapp.projects')),
                ('reporting_manager_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_managerref', to='eztimeapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Timespent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodaysApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('saved_on', models.CharField(blank=True, max_length=250, null=True)),
                ('approved_status', models.CharField(blank=True, max_length=250, null=True)),
                ('action', models.CharField(blank=True, max_length=250, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization')),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.people')),
                ('timesheets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='m1.timesheets')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetsApprovalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_period', models.CharField(blank=True, max_length=250, null=True)),
                ('approval_period_in_days', models.CharField(blank=True, max_length=250, null=True)),
                ('grace_days_to_approve', models.CharField(blank=True, max_length=250, null=True)),
                ('auto_approve', models.BooleanField(default=False)),
                ('active_status', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_date_time', models.DateTimeField(null=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_approved_by_user', to='eztimeapp.customuser')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization')),
            ],
        ),
    ]
