# Generated by Django 3.2.10 on 2023-06-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheets',
            name='applied_date_timestamp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='task_worked_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
