# Generated by Django 3.2.10 on 2023-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0002_auto_20230621_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheets',
            name='time_spent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
