# Generated by Django 3.2.10 on 2023-06-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0018_leaveapplication_request'),
        ('m1', '0003_alter_timesheets_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheets',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.customuser'),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='approved_date_timestamp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='approved_state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
