# Generated by Django 3.2.10 on 2023-06-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0004_auto_20230621_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheets',
            name='status',
        ),
    ]
