# Generated by Django 3.2.10 on 2023-06-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0005_remove_timesheets_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheets',
            name='task',
        ),
        migrations.AddField(
            model_name='timesheets',
            name='project_category',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
