# Generated by Django 3.2.10 on 2023-06-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0006_auto_20230621_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheets',
            name='applied_date',
            field=models.DateTimeField(null=True),
        ),
    ]
