# Generated by Django 3.2.10 on 2023-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0007_timesheets_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheets',
            name='applied_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
