# Generated by Django 3.2.10 on 2023-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0009_auto_20230705_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetsapprovalconfig',
            name='approval_period_in_days',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
