# Generated by Django 3.2.10 on 2023-07-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0010_timesheetsapprovalconfig_approval_period_in_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheets',
            name='approved_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
