# Generated by Django 3.2.10 on 2023-12-03 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eztimeapp', '0027_auto_20231203_1803'),
        ('m1', '0011_timesheets_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheets',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
        migrations.AddField(
            model_name='todaysapproval',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eztimeapp.organization'),
        ),
    ]
