name: Check Server Connection

on:
  workflow_dispatch:
    inputs:
      server_host:
        description: '165.232.181.49'
        required: true
      server_user:
        description: 'root'
        required: true
      server_password:
        description: 'EkfraZo@123#E'
        required: true
  push:
    branches:
      - main
concurrency:
  group: main
  cancel-in-progress: true
  
jobs:
  quality-assurance:
    name: Quality Assurance
    uses: ./.github/workflows/pr.yml

  check-connection:
    name: Check connection to server
    needs: quality-assurance

    runs-on: ubuntu-latest

    steps:
      - name: Check Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.HOST_PASS }}
          command: 'echo "Connection successful"'

